[package]
name = "cargo-doc2readme"
version = "0.0.0"
publish = false
authors = ["Dominic <git@msrd0.de>"]
edition = "2018"
repository = "https://github.com/msrd0/cargo-doc2readme"
license = "Apache-2.0"

[dependencies]
anyhow = "1.0"
cargo = "0.53.0"
clap = "3.0.0-beta.2"
once_cell = "1.7"
pulldown-cmark = { version = "0.8", default-features = false }
regex = "1.5"
semver = "0.11"
syn = { version = "1.0", default-features = false }
tera = "1.8"
unindent = "0.1.7"
url = "2.2"

[dev-dependencies]
indoc = "1.0"
pretty_assertions = "0.7"

[profile.release]
lto = true
opt-level = "z"
